services:
  - type: web
    name: social-downloader-test
    env: node
    plan: free
    buildCommand: |
      npm install
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
      chmod +x yt-dlp
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    autoDeploy: true